apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomodule
  labels:
    app: gomodule
  namespace: namespace-workflow-1678734449814
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gomodule
  template:
    metadata:
      labels:
        app: gomodule
    spec:
      containers:
        - name: gomodule
          image: acrworkflow1678734449814.azurecr.io/image-workflow-1678734449814:latest
          ports:
            - containerPort: 80